# Generated by Django 4.2.15 on 2024-10-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameblog', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
